### ISSUE TITLE
error 111

### ISSUE THREAD

**Issue by Jau-Al** [makehumancommunity/makehuman-plugin-for-blender#46]
Hello,
I tried installing the plugin in my Blender 2.8 on Ubuntu 18.04LTS.
It couldn't connect. I'm using the community PPA.
I tried a bunch of ports. Nothing.

![Screenshot from 2019-05-10 14-59-07](https://user-images.githubusercontent.com/15030964/57529217-a5488e00-7334-11e9-908f-8d3306e79b31.png)
![Screenshot from 2019-05-10 15-01-17](https://user-images.githubusercontent.com/15030964/57529220-a7125180-7334-11e9-90e0-a0b7af9e7a12.png)

```
makehuman-community/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Free, open source tool for creating realistic 3D human characters.

makehuman-community-3dobjs-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw files for the base mesh.

makehuman-community-blendertools/bionic,bionic 1.2.0+20190317213847-1ppa1 all
  MakeHuman integration scripts for Blender.

makehuman-community-bodyparts/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Bodyparts for MakeHuman.

makehuman-community-bodyparts-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw obj files for MakeHuman bodyparts.

makehuman-community-clothes/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Clothes for MakeHuman.

makehuman-community-clothes-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw obj and mhclo files for MakeHuman clothes.

makehuman-community-docs/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Autogenerated documentation for MakeHuman.

makehuman-community-hair/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Hair for MakeHuman.

makehuman-community-hair-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw obj files for MakeHuman hair.

makehuman-community-plugins-assetdownloader/bionic,bionic,now 20190319184908-1ppa1 all [installed]
  Asset downloader functionality for MakeHuman.

makehuman-community-plugins-massproduce/bionic,bionic,now 20190310125113-1ppa1 all [installed]
  Mass randomization for makehuman.

makehuman-community-plugins-mhapi/bionic,bionic,now 20190310125057-1ppa1 all [installed]
  The MHAPI library for MakeHuman.

makehuman-community-plugins-socket/bionic,bionic,now 20190310125108-1ppa1 all [installed]
  Socket server for MakeHuman

makehuman-community-proxymeshes-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw obj and proxy files for MakeHuman proxies.

makehuman-community-skins/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Skins for MakeHuman

makehuman-community-targets/bionic,bionic,now 1.2.0+20190317213847-1ppa1 all [installed]
  Body modifiers for MakeHuman.

makehuman-community-targets-dev/bionic,bionic,now 1.2.0+20190310124855-1ppa1 all [installed]
  Raw targets for MakeHuman.

```

**Comment by joepal1976** [comment]
It would seem you have changed the listen port on the makehuman side to 66666. This won't work since the maximum port number allowed by TCP is 65535. 

Does it work if you change the port number back to 12345? You should probably start/stop the socket listener after changing the port number.

**Comment by Jau-Al** [comment]
Lol sorry the 66666 was me getting a bit crazy after a dozen try and fails :-p . I just reinstalled everything Makehuman and Blender 2.8 from PPAs and now it works.
Except for an error when I click Import :
![Screenshot from 2019-05-10 21-53-16](https://user-images.githubusercontent.com/15030964/57553326-7fd87600-736e-11e9-96c8-4bc129517dc7.png)
The Character mesh is imported but not the rig.
![Screenshot from 2019-05-10 22-02-31](https://user-images.githubusercontent.com/15030964/57553624-5c61fb00-736f-11e9-955c-09ef61c5bb25.png)

**Comment by Aranuvir** [comment]
The screenshot of your error message is incomplete. Please do not post screenshots of error messages. Best run Blender from a shell (Bash) and copy/paste the error text printed to the shell.

**Comment by joepal1976** [comment]
It's possible you're running into the same problem as https://github.com/makehumancommunity/makehuman-plugin-for-blender/issues/45, but it's difficult to say from the screenshot. For stack traces, the _last_ lines are the interesting ones, not the first ones. And we can't see the last lines in the screenshot. 

As Aranuvir says, it'd be easier to debug this if we got a textual stack trace rather than a screenshot.

**Comment by Jau-Al** [comment]
Ok, found it ! It's Topology Male1591. If I use the basic one, it works.
Terminal outputs :
[MHSyncBlenderBug.log](https://github.com/makehumancommunity/makehuman-plugin-for-blender/files/3172531/MHSyncBlenderBug.log)
[BlenderSyncMHBug.log](https://github.com/makehumancommunity/makehuman-plugin-for-blender/files/3172532/BlenderSyncMHBug.log)

**Comment by joepal1976** [comment]
Ok, this is enough information to work with. 

Question though: exactly what blender are you using? As in where did you get it and how did you install it? As it is spitting out a bunch of error messages about numpy, it would seem you have a faulty blender installation. This is probably (but not 100% sure) not related to the makehuman import error, but it is bound to cause you additional trouble in the longer run.

**Comment by joepal1976** [comment]
For further reference: It does not crash for me with Male1591 + game engine + toon01. 

Could you try downloading the latest blender 2.80 from blender's home page and see if it works when using that?

Note that using blender versions from Ubuntu rather than from Blender is more than likely to cause problems.

**Comment by Aranuvir** [comment]
> For further reference: It does not crash for me with Male1591 + game engine + toon01.
>
+1. BTW, there is currently no toon shader setup with the transfer tool.

**Comment by Jau-Al** [comment]
Thomas is doing a great job at maintaining the PPA, but I tried with the last build.
Here is the output and the Makehuman project file.

```
~/StandAloneApps/blender-2.80-9efe117535c6-linux-glibc224-x86_64$ ./blender
Read prefs: /home/psychojau/.config/blender/2.80/config/userpref.blend
found bundled python: /home/psychojau/StandAloneApps/blender-2.80-9efe117535c6-linux-glibc224-x86_64/2.80/python
archipack: ready

 Starting Auto-Rig Pro Functions... 


 Starting Auto-Rig Pro...

Blender version:  2.80 (sub 71)

 Starting Auto-Rig Pro: Smart... 


 Starting Auto-Rig Pro: Remap... 


 Starting Auto-Rig Pro: Game Engine Exporter... 

Loading MH community plug-in v 0.4
Loading sync plug-in
sync plug-in loaded
Loading kinect Sensor plug-in
kinect Sensor plug-in loaded
MH community plug-in load complete
Warning: class AnimationProps contains a properties which should be an annotation!
/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/kinect_sensor/kinect_ui.py:19
    make annotation: AnimationProps.id
    make annotation: AnimationProps.name
Loading maketarget v 1.1.0
pose.py reloaded
MakeTarget loaded
Traceback (most recent call last):
  File "/home/psychojau/StandAloneApps/blender-2.80-9efe117535c6-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'makeclothes'
Info: Deleted 1 object(s)

Import body
GROUND MEAN: -0.8285502910614014
WARNING: face index 18486 > 18486
Creating new material body
Importing proxy: Low-Poly
Creating new material Low-Poly
Importing proxy: male1591
Traceback (most recent call last):
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/operators/bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 90, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 131, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 164, in gotVerticesData
    FetchServerData('getBodyFacesBinary',self.gotFacesData,True)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 193, in gotFacesData
    FetchServerData('getBodyTextureCoordsBinary', self.gotTextureCoords, True)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 211, in gotTextureCoords
    FetchServerData('getBodyFaceUVMappingsBinary', self.gotFaceUVMappings, True)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 245, in gotFaceUVMappings
    self.afterMeshData()
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 387, in afterMeshData
    FetchServerData('getBodyMaterialInfo',self.gotBodyMaterialInfo)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 403, in gotBodyMaterialInfo
    FetchServerData('getSkeleton', self.gotSkeleton)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 480, in gotSkeleton
    FetchServerData('getProxiesInfo', self.gotProxiesInfo)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 486, in gotProxiesInfo
    self.importNextProxy()
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 494, in importNextProxy
    ImportProxyBinary(self.obj, self.name, self.proxiesInfo[self.nextProxyToImport], self.proxyLoaded, self.collection)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 106, in __init__
    FetchServerData('getProxyVerticesBinary', self.gotVerticesData, expectBinary=True, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 147, in gotVerticesData
    FetchServerData('getProxyFacesBinary',self.gotFacesData, expectBinary=True, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 179, in gotFacesData
    FetchServerData('getProxyTextureCoordsBinary', self.gotTextureCoords, expectBinary=True, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 198, in gotTextureCoords
    FetchServerData('getProxyFaceUVMappingsBinary', self.gotFaceUVMappings, expectBinary=True, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 232, in gotFaceUVMappings
    self.afterMeshData()
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 318, in afterMeshData
    FetchServerData('getProxyMaterialInfo', self.gotProxyMaterialInfo, expectBinary=False, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 338, in gotProxyMaterialInfo
    self.onFinished(self)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 529, in proxyLoaded
    self.importNextProxy()
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 494, in importNextProxy
    ImportProxyBinary(self.obj, self.name, self.proxiesInfo[self.nextProxyToImport], self.proxyLoaded, self.collection)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 106, in __init__
    FetchServerData('getProxyVerticesBinary', self.gotVerticesData, expectBinary=True, params={ "uuid": self.proxyInfo["uuid"] })
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/psychojau/.config/blender/2.80/scripts/addons/MH_Community/mh_sync/import_proxy_binary.py", line 121, in gotVerticesData
    assert(iMax == int(self.proxyInfo["numVertices"]))
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1

```

[buggyman.tar.gz](https://github.com/makehumancommunity/makehuman-plugin-for-blender/files/3200104/buggyman.tar.gz)

**Comment by Aranuvir** [comment]
Once I had the same problem with a proxy. But the next time I tried it the error had vanished and I wasn't able to reproduce it.

**Comment by steveday4u** [comment]
The problem occurs when the smooth button is enabled in MH. Disable smooth and the import should work.
