### ISSUE TITLE
Scene object has no attribute update

### ISSUE THREAD

**Issue by j2l** [makehumancommunity/makehuman-plugin-for-blender#48]
It worked in alpha1 but seems broken now:

- Mesh > Import human
- Rig > No Location Translation
- MH, set new pose
- Sync with MH
- in decimeter and "default no toes" skeleton

```
armature exported units is DECIMETERS, headTail: -0.8399094343185425, footTail: -8.53725528717041
Update pose
Traceback (most recent call last):
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\operators\posesync.py", line 22, in execute
    SyncPose()
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\mh_sync\sync_pose.py", line 22, in __init__
    self.executeJsonCall()
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\mh_sync\sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\mh_sync\sync_pose.py", line 43, in callback
    self.apply(bone, json_obj, bpy.context.scene.MhNoLocation)
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\mh_sync\sync_pose.py", line 62, in apply
    bpy.context.scene.update()
AttributeError: 'Scene' object has no attribute 'update'

location: <unknown location>:-1

location: <unknown location>:-1
```

Or I missed something

**Comment by Palmer-JC** [comment]
This was due to a last minute change to the Blender 2.80 API.  Latest should have all API issues for Blender 2.80 taken care of, plus:

- expressions now work for any scale human
- Kinect runs for Blender 2.80, still issues, but runs

**Comment by j2l** [comment]
That is good news!
Thanks, you made my day :)

**Comment by j2l** [comment]
@Palmer-JC thanks!
(I'm not sure comments on closed tickets are notified)
