### ISSUE TITLE
Plugin crashes on re-register

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman-plugin-for-blender#54]
When deactivating and reactivating the add-on in the preference panel there is an exception:

> Exception in module register(): $HOME/.config/blender/2.80/scripts/addons/MH_Community/__init__.py
> Traceback (most recent call last):
>   File "$HOME/Programme/blender-2.80/2.80/scripts/modules/addon_utils.py", line 384, in enable
>     mod.register()
>   File "$HOME/.config/blender/2.80/scripts/addons/MH_Community/__init__.py", line 102, in register
>     registerKinectConstantsAndSettings()
>   File "$HOME/.config/blender/2.80/scripts/addons/MH_Community/kinect_sensor/kinect_ui.py", line 18, in registerKinectConstantsAndSettings
>     bpy.utils.register_class(MHC_UL_AnimationItems)
> ValueError: register_class(...): already registered as a subclass

**Comment by Aranuvir** [comment]
There's a bug fix, needs testing...

**Comment by Aranuvir** [comment]
I guess it's tested enough, closing...
