### ISSUE TITLE
Compatibility with Blender 2.81

### ISSUE THREAD

**Issue by AmmarkoV** [makehumancommunity/makehuman-plugin-for-blender#59]
Blender 2.81 is out and this is a feature request for a compatible version of the plugin
https://www.blender.org/download/releases/2-81/

Trying the version for Blender 2.80 I get the following output on Import

![2019-11-25-181946_3840x1080_scrot](https://user-images.githubusercontent.com/97630/69558100-53094a80-0fb0-11ea-9835-7bdc0e14ea7e.png)

Thank you for your awesome work..

**Comment by AmmarkoV** [comment]
Also this is blender output in text format.. 

bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
Modules Installed (MH_Community) from '/home/ammar/Programs/MH_Community_for_blender_280.zip' into '/home/ammar/.config/blender/2.81/scripts/addons'
Modules Installed (Diffeomorphic-makewalk-477bc620c069) from '/home/ammar/Programs/Diffeomorphic-makewalk-477bc620c069.zip' into '/home/ammar/.config/blender/2.81/scripts/addons'
Traceback (most recent call last):
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/operators/bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 84, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 141, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 147, in gotVerticesData
    shape = self.bodyInfo["verticesShape"]
KeyError: 'verticesShape'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/operators/bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 84, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 141, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 147, in gotVerticesData
    shape = self.bodyInfo["verticesShape"]
KeyError: 'verticesShape'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/operators/bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 84, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 141, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 147, in gotVerticesData
    shape = self.bodyInfo["verticesShape"]
KeyError: 'verticesShape'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/operators/bodyimport.py", line 14, in execute
    ImportBodyBinary()
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 84, in __init__
    FetchServerData('getBodyMeshInfo', self.gotBodyInfo)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 14, in callback
    self.readyFunction(json_obj.data)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 141, in gotBodyInfo
    FetchServerData('getBodyVerticesBinary',self.gotVerticesData,True)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 8, in __init__
    self.executeJsonCall(expectBinaryResponse=expectBinary, params=params)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/sync_ops.py", line 18, in executeJsonCall
    self.callback(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/fetch_server_data.py", line 12, in callback
    self.readyFunction(json_obj)
  File "/home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py", line 147, in gotVerticesData
    shape = self.bodyInfo["verticesShape"]
KeyError: 'verticesShape'

location: <unknown location>:-1

**Comment by joepal1976** [comment]
Ouch. Ok, I haven't had time to try 2.81 yet. 

Did it work for you with 2.80 before trying to install it in 2.81?

**Comment by AmmarkoV** [comment]
Yes :)

**Comment by joepal1976** [comment]
Unfortunately, I cannot reproduce this error. I've tried with characters both with and without clothes. I'm running 2.81 on linux, which seems to be the same as you.

Can you try downloading the latest makehuman plugin for blender and try again? It's available as a plugin zip here: http://download.tuxfamily.org/makehuman/plugins/

If the problem persist, is there any other information you can provide? Such as exactly what did you have in MH when trying to import?

The error does not concern syntax which have changed between 2.80 and 2.81. It seems you got a malformed response from MakeHuman, so that there was no information about the shape of the array containing vertex data. I currently have no hypothesis about why this would happen. 

If you're comfortable with it, it'd be helpful if you edited /home/ammar/.config/blender/2.81/scripts/addons/MH_Community/mh_sync/import_body_binary.py and added the following on line 146:

`    pp.pprint(self.bodyInfo)`

This way we could get information about how the response from MakeHuman looked.

**Comment by Aranuvir** [comment]
> Unfortunately, I cannot reproduce this error.
+1

**Comment by AmmarkoV** [comment]
Good to know that it is compatible with 2.81 I will add the extra line and attach the log.

**Comment by AmmarkoV** [comment]
![2019-12-05-144020_3840x1080_scrot](https://user-images.githubusercontent.com/97630/70236252-41246600-176d-11ea-89e3-77bfe7799464.png)

Downloading the file from here ( http://download.tuxfamily.org/makehuman/plugins/makehuman-plugin-for-blender-latest.zip )works with Blender 2.81,
Thank you!
