### ISSUE TITLE
can't install 0.6.2 on 2.80

### ISSUE THREAD

**Issue by j2l** [makehumancommunity/makehuman-plugin-for-blender#63]
Happy new year!

It installs fine on 2.81, but on 2.80 (Win 10):
```
Loading MH community plug-in v 0.6.2
Traceback (most recent call last):
  File "C:\Users\nobody\Documents\blender-2.80\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\__init__.py", line 29, in <module>
    from .mh_sync.importer_ui import addImporterUIToTab, registerImporterConstantsAndSettings, addImporterSettingsToTab
ImportError: cannot import name 'addImporterSettingsToTab' from 'MH_Community.mh_sync.importer_ui' (C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\mh_sync\importer_ui.py)
```

**Comment by j2l** [comment]
After restarting it installed. Weird

**Comment by Aranuvir** [comment]
Even if it had not worked with B280 anymore, we wouldn't have fixed that issue. Supporting multiple Blender versions is rather cumbersome and B280 is no longer the recent version....
