### ISSUE TITLE
Seperate Eyes does not function

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman-plugin-for-blender#70]
0.6.3 When directly 'importing human', the 'seperate eyes' button is greyed out, and is not activatable under any attempts. Makehuman nightly, tried on blender 2.82a and 2.90 alpha

**Comment by Totoro83** [comment]
I have a possibly related problem, when I try to split the eyes (I can do this only immediately after I imported the geometry) I obtain an error:

```
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.origin_set(type='ORIGIN_CENTER_OF_MASS', center='MEDIAN')
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.mh_community.separate_eyes()
Traceback (most recent call last):
  File "C:\Users\Totoro\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MH_Community\operators\separateeyes.py", line 17, in execute
    SeparateEyes(context.object)
  File "C:\Users\Totoro\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MH_Community\separate_eyes.py", line 35, in __init__
    left.select = True
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1
```

**Comment by Hunanbean** [comment]
Seperate Eyes is now functioning when using the proper skeletons, but has errors as follows:

`Error: Traceback (most recent call last):
  File "C:\Users\Waterspell\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MH_Community\operators\separateeyes.py", line 17, in execute
    SeparateEyes(context.object)
  File "C:\Users\Waterspell\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MH_Community\separate_eyes.py", line 35, in __init__
    left.select = True
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1`


It actually does seperate the eyes though

**Comment by Aranuvir** [comment]
Providing a fix. This will break backward compatibility. Leaving this task open, if BWC is still desired. In that case we could also discuss, if we want an eye selected after that process anyway...

**Comment by Aranuvir** [comment]
Not further input, closing finally...
